# menu
menu:
  Home: .
  Archives: archives  # 归档
  Categories: categories  # 分类
  Tags: tags  # 标签
  # Repository: https://github.com/LLye-hub  # github repositories
  # Links: links  # 友链
  About: about  # 关于

# Enable/Disable menu icons
menu_icons:
  enable: true  # 是否启用导航菜单图标
  home: icon-home-fill
  archives: icon-archives-fill
  categories: icon-folder
  tags: icon-tags
  repository: icon-project
  books: icon-book-fill
  links: icon-friendship
  about: icon-cup-fill

# rss
rss: /atom.xml

# Site
site:
  logo:
    enabled: false
    width: 40
    height: 40
    url: ../images/avatar.jpg
  title: Hexo # 页面title
  favicon: images/avatar.jpeg
  board: <p>欢迎交流与分享经验!</p> # 站点公告
  copyright: true # 底部版权信息

# config
config:
  skin: theme-purple # 主题颜色 theme-black theme-blue theme-green theme-purple
  layout: main-center # 布局方式 main-left main-center main-right
  toc: true # 是否开启文章章节目录导航
  menu_highlight: true # 是否开启当前菜单高亮显示
  thumbnail: false # 是否开启文章缩略图，enable posts thumbnail, options: true, false
  excerpt_link: Read More
  #New
  isNewTabLinks: true #是否链接打开新标签页
  autoUnfold: true # 默认展开文章目录

# Pagination
pagination:
  number: true
  prev: 
    alwayShow: true
  next:
    alwayShow: true
  midSize: 3 # 当前页码左右到省略号显示的页码数，默认2，表现为 1 ... 4 5 6 7 8 ... 10
  showContent: true # 页面文章小于2篇时显示文章内容

# Sidebar
sidebar: right
widgets:
  - board  
  - archive
  - category
  - tag
  # - tagcloud
  - recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive  

# widget behavior
archive_type: 'monthly'     # 归档文章显示方式
show_count: true

# Fancybox
fancybox: false

# Search
search:
  insight: true # you need to install `hexo-generator-json-content` before using Insight Search
  baidu: true # you need to disable other search engines to use Baidu search

# Donate
donate:
  enable: true
  # 微信打赏
  wechatpay:
    qrcode: images/donate/wechatpayimg.jpeg
    title: 微信支付
  # 支付宝打赏
  alipay: 
    qrcode: images/donate/alipayimg.jpeg
    title: 支付宝

# Share 文章分享
# weibo,qq,qzone,wechat,tencent,douban,diandian,facebook,twitter,google,linkedin
share:
  enable: true  # 是否启用分享
  sites: weibo,qq,wechat,facebook,twitter  # PC端显示的分享图标
  mobile_sites: weibo,qq,wechat  # 移动端显示的分享图标

# Github
# github: 
#   username: cofess  # github username

# Repository Info (This will override 'github' option)
# 项目仓库信息（将会覆盖 github 项）
repository:
  platform: github # 托管平台（github | gitee）
  username: LLye-hub # 用户名

# Comment
# Gitment
# Introduction: https://imsun.net/posts/gitment-introduction/
comment:
  type: valine  # 启用哪种评论系统
  disqus:  # enter disqus shortname here
  youyan: 
    uid:  # enter youyan uid 
  livere:
    uid: # enter youyan uid 
  gitment:
    githubID: 
    repo: 
    ClientID: 
    ClientSecret: 
    lazy: false
  gitalk: # gitalk. https://gitalk.github.io/
    owner:  #必须. GitHub repository 所有者，可以是个人或者组织。
    admin:  #必须. GitHub repository 的所有者和合作者 (对这个 repository 有写权限的用户)。
    repo:  #必须. GitHub repository.
    ClientID:  #必须. GitHub Application Client ID.
    ClientSecret:  #必须. GitHub Application Client Secret.
    enableHotKey: true
    language: zh-CN
    
  valine: # Valine. https://valine.js.org/quickstart.html
    appid: j0NAwHf3A34KzcPo5xsl4eNQ-gzGzoHsz  # your leancloud application appid
    appkey: VLwhImvGCHAwwqQ18j9mlE0G  # your leancloud application appkey
    notify: true # mail notifier , https://github.com/xCss/Valine/wiki
    verify: true # Verification code
    placeholder: Just go go # comment box placeholder
    avatar: mm # gravatar style
    meta: nick,mail,link # custom comment header
    pageSize: 5 # pagination size
    visitor: true # Article reading statistic https://valine.js.org/visitor.html

# douban 豆瓣书单
# Api：
  # https://developers.douban.com/wiki/?title=book_v2 图书
  # https://developers.douban.com/wiki/?title=movie_v2 电影
# books：  
  # https://api.douban.com/v2/book/user/:name/collections?start=0&count=100 个人书单列表
# movies: 
  # https://api.douban.com/v2/movie/in_theaters 正在上映的电影
  # https://api.douban.com/v2/movie/coming_soon 即将上映的电影
  # https://api.douban.com/v2/movie/subject/:id 单个电影信息
  # https://api.douban.com/v2/movie/search?q={text} 电影搜索
douban:
  user: # 豆瓣用户名
  start: 0 # 从哪一条记录开始
  count: 100 # 获取豆瓣书单数据条数
  apikey: # 豆瓣apikey
  
# PV
pv:
  busuanzi:
    enable: true  # 不蒜子统计
  leancloud:
    enable: true  # leancloud统计
    app_id: j0NAwHf3A34KzcPo5xsl4eNQ-gzGzoHsz # leancloud <AppID>
    app_key: VLwhImvGCHAwwqQ18j9mlE0G # leancloud <AppKey>
        
# wordcount
postCount:
  enable: true
  wordcount: true  # 文章字数统计
  min2read: true  # 阅读时长预计 

# Plugins
plugins:
  google_analytics: # enter the tracking ID for your Google Analytics
  google_site_verification: # enter Google site verification code
  baidu_analytics: # enter Baidu Analytics hash key
  tencent_analytics: 

# mermaid chart  https://github.com/webappdevelp/hexo-filter-mermaid-diagrams
mermaid: ## mermaid url https://github.com/knsv/mermaid
  enable: true  # default true
  version: "8.13.8" # default v7.1.2
  options:  # find more api options from https://github.com/knsv/mermaid/blob/master/src/mermaidAPI.js
  #startOnload: true  // default true

# Miscellaneous
twitter:
google_plus:
fb_admins:
fb_app_id:  
  
# profile
profile:
  enabled: true # Whether to show profile bar
  articleSelfBlock: false # 是否开启文章下方的自我介绍
  avatar: images/avatar.jpeg
  gravatar:  # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
  author: 辣白菜的菜
  author_title: 数仓开发工程师
  author_description: 持续成长的小白菜，搞钱要紧，早日退休 # 个人简介标语，可为null
  location: HangZhou, China
  follow: https://github.com/LLye-hub
  # Social Links
  social:
    links:
      github: https://github.com/LLye-hub
    link_tooltip: true # enable the social link tooltip, options: true, false


  # My Skills 
  skills:
    SQL: ★★★★☆
    Hadoop: ★★☆☆☆
    Spark: ★★☆☆☆
    Git: ★★★☆☆
    Java: ★☆☆☆☆
  # My Personal socials
  socials:
    Github: https://github.com/LLye-hub
#    Blog: https://llye-hub.github.io/
    CSDN: https://blog.csdn.net/weixin_44115164?spm=1000.2115.3001.5343
    Email: yelilun@163.com
  # My Personal Works
  # works:
  #   nam4e:
  #     link: https://github.com/LLye-hub
  #     date: 2021
  # My Personal Projects
  # projects:
  #   cofess/gulp-startpro: https://github.com/cofess/gulp-startpro
  #   cofess/hexo-theme-pure: https://github.com/cofess/hexo-theme-pure
  # copyright: false # 底部版权信息
  # My Personal Labels
  labels:
    - sql
    - 数仓开发
    - hadoop
    - hive
    - spark
    - java

